
const TOTAL_ROWS = 100000;
const TOTAL_COLS = 500;
const DEFAULT_COLUMN_WIDTH = 100;
const DEFAULT_ROW_HEIGHT = 30;
const HEADER_COLUMN_WIDTH=100;
const HEADER_ROW_HEIGHT=30;

export {TOTAL_ROWS,TOTAL_COLS,DEFAULT_COLUMN_WIDTH,DEFAULT_ROW_HEIGHT,HEADER_COLUMN_WIDTH,HEADER_ROW_HEIGHT}